CommIdiomas:
  app: Comm
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  fieldGeneratorUrlFriendly: Codigo
  fieldGeneratorMetatagTitle: Codigo
  controller: CONTROLADOR
  action: ACTION
  template: TEMPLATE
  parametros: PARAMETROS
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Idiomas
  id_video: commidiomas
  url_video: null
  feature_list: YES
  conection: 
  entity: CommIdiomas
  table: CommIdiomas
  primarykey: Id
  linkBy: ''
  records_per_page: 20
  order_by:
    -
      title: 'Idioma a-z'
      criteria: 'Idioma ASC'
    -
      title: 'Idioma z-a'
      criteria: 'Idioma DESC'
  search_default: Id
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    Codigo:
      title: Codigo
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Idioma:
      title: Idioma
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
