CommPaises:
  app: Comm
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  fieldGeneratorUrlFriendly: Codigo
  fieldGeneratorMetatagTitle: Codigo
  controller: Paises
  action: Index
  template: Index
  parametros: null
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Paises
  id_video: commpaises
  url_video: null
  feature_list: YES
  conection: 
  entity: CommPaises
  table: CommPaises
  primarykey: Id
  linkBy: ''
  records_per_page: 20
  order_by:
    -
      title: 'Pais a-z'
      criteria: 'Pais ASC'
    -
      title: 'Pais z-a'
      criteria: 'Pais DESC'
  search_default: Id
  referenced_entities:
    - CommMonedas
    - CommZonasHorarias
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    Codigo:
      title: Código
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Pais:
      title: País
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    IdMoneda:
      title: Moneda
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Moneda, entity: CommMonedas, method: fetchAll, params: Moneda, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '20', min: null, max: null, message: 'Valor Requerido' }
    IdZonaHoraria:
      title: 'Zona Horaria'
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: 'Zona Horaria', entity: CommZonasHorarias, method: fetchAll, params: Zona, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '20', min: null, max: null, message: 'Valor Requerido' }
    Latitud:
      title: Latitud
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: false, min: null, max: null, message: 'Valor Requerido' }
    Longitud:
      title: Longitud
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: false, min: null, max: null, message: 'Valor Requerido' }
