CommImpuestos:
  app: Comm
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  fieldGeneratorUrlFriendly: IdPais
  fieldGeneratorMetatagTitle: IdPais
  controller: CONTROLADOR
  action: ACTION
  template: TEMPLATE
  parametros: PARAMETROS
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Impuestos
  id_video: commimpuestos
  url_video: null
  feature_list: YES
  conection: 
  entity: CommImpuestos
  table: CommImpuestos
  primarykey: Id
  linkBy: ''
  records_per_page: 20
  order_by:
    -
      title: 'Nombre a-z'
      criteria: 'Nombre ASC'
    -
      title: 'Nombre z-a'
      criteria: 'Nombre DESC'
  search_default: Id
  referenced_entities:
    - CommPaises
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    IdPais:
      title: País
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Pais, entity: CommPaises, method: fetchAll, params: Pais, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Nombre:
      title: Nombre
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Valor:
      title: Valor
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Recargo:
      title: Recargo
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Retencion:
      title: Retención
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
