# cpanel/entities/schema.yml

core_aplicaciones:
  engine:
  charSet:
  comment:
  columns:
    CodigoApp:   {type: string(15), notnull: true, index: unique}
    NombreApp:   {type: string(100), notnull: true}
    Descripcion: {type: string(100), notnul: true}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_imagenes:
  columns:
    Entidad:    { type: string(255), notnull: true}
    IdEntidad:  { type: integer(11), notnull: true}
    EsGaleria:  { type: boolean, notnull: true, default: 0, index: index, comment: 'abstract,ValoresSN,IDTipo' }
    PathName:   { type: string(255), notnull: true}
    TextoPie:   { type: string(255), notnull: false}
    Title:      { type: string(255), notnull: false}
    Alt:        { type: string(255), notnull: false}
    IdTipoMime: { type: string(10), notnull: false, index: index, comment: 'Abstract,TiposMime,IDTipo' }
    Peso:       { type: int(11), notnull: true, default: 0}
    Alto:       { type: int(11), notnull: true, default: 0}
    Ancho:      { type: int(11), notnull: true, default: 0}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_modulos:
  columns:
    CodigoApp:       { type: string(15), notnull: true, index: index, comment: 'db,core_aplicaciones,CodigoApp' }
    NombreModulo:    { type: string(255), notnull: true, index: unique }
    Nivel:           { type: integer(4), notnull: true, default: 0 }
    PerteneceA:      { type: string(255), notnull: false, default: NULL, index: index}
    Titulo:          { type: string(100), notnull: true }
    Descripcion:     { type: string(100), notnull: false, default: NULL }
    Funcionalidades: { type: string(255), notnull: true }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_perfiles:
  columns:
    Perfil: { type: string(50), notnull: true }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_permisos:
  columns:
    IdPrefil:        { type: integer, notnull: true, index: index, comment: 'db,core_perfiles,Id' }
    NombreModulo:    { type: string(255), notnull: true, index: index, comment: 'db,core_modulos,NombreModulo' }
    Funcionalidades: { type: string(255), notnull: true }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_roles:
  columns:
    Rol: { type: string(50), notnull: true }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_tiposFuncionalidad:
  columns:
    Codigo: { type: string(15), notnull: true, index: unique}
    Titulo: { type: string(100), notnull: true}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_usuariosTipos:
  columns:
    Descripcion: { type: string(50), notnull: true}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_urlAmigables:
  columns:
    Controller:    { type: string(255), notnull: true }
    Action:        { type: string(255), notnull: true }
    Template:      { type: string(255), notnull: false, default: NULL }
    Parametros:    { type: string(255), notnull: false, default: NULL }
    Entidad:       { type: string(255), notnull: true}
    IdEntidad:     { type: integer(11), notnull: true}
    NumeroVisitas: { type: integer(11), notnull: true, default: 0}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

core_usuarios:
  columns:
    IdPerfil:       {type: int(11), notnull: true, index: index, comment: 'db, core_perfiles, Id' }
    IdRol:          {type: int(11), notnull: true, index: index, comment: 'db, core_roles, Id' }
    IdTipoUsuario:  {type: int(11), notnull: true, index: index, comment: 'db, core_tiposUsuarios, Id' }
    Login:          { type: string(50), notnull: true }
    Password:       { type: string(100), notnull: true }
    Apellidos:      { type: string(100), notnull: true, index: index}
    Nombre:         { type: string(100), notnull: true }
    Email:          { type: string(100), notnull: false, default: NULL }
    TelefonoMovil:  { type: string(25), notnull: false, default: NULL }
    CambioPassword: { type: boolean, notnull: true, default: 0, comment: 'Abstract, ValoresSN, IDTipo' }
    Ips:            { type: string(255), notnull: false, default: NULL}
    NLogin:         { type: integer(4), default: 0 }
    UltimoLogin:    { type: datetime, default: '0000-00-00 00:00:00' }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

# ----------------------
# APP ENLACES DE INTERES
# ----------------------
enl_enlaces:
  columns:
    IdSeccion:    { type: int(11), notnull: true, index: index, comment: 'db, enl_secciones, Id' }
    Titulo:       { type: string(255), notnull: true }
    Subtitulo:    { type: string(255), notnull: false, default: NULL }
    Url:          { type: string(255), notnull: false, default: NULL }
    TargetBlank:  { type: boolean, notnull: true, default: 0, index: index, comment: 'Abstract, ValoresSN, IDTipo' }
    EsHttps:      { type: boolean, notnull: true, default: 0, index: index, comment: 'Abstract, ValoresSN, IDTipo' }
    EsUrlInterna: { type: boolean, notnull: true, default: 0, index: index, comment: 'Abstract, ValoresSN, IDTipo' }
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations:

enl_secciones:
  columns:
    Titulo:      { type: string(255), notnull: true}
    Subtitulo:   { type: string(255), notnull: false, default: NULL }
    TipoSeccion: { type: tinyint(1), notnull: true, default: 0, index: index, comment: 'Abstract,,TipoSeccionEnlacesInteres,IDTipo' }
    PerteneceA:  { type: int(11), notnull: true, comment: 'db, enl_secciones, Id'}
    Entidad:     { type: string(255), notnull: true}
    IdEntidad:   { type: integer(11), notnull: true}
    <?php include '../cpanel/entities/schemaComunes.yml'; echoln('');?>
  relations: