# Module: CoreFuncionalidades
# Document : modules\CoreFuncionalidades\config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 05.09.2012 08:17:43
#
---
CoreFuncionalidades:
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  feature_list: YES
  help_file: help.html.twig
  title: CoreFuncionalidades
  id_video: corefuncionalidades
  url_video: null
  conection: 'cpanel'
  entity: CoreFuncionalidades
  table: CoreFuncionalidades
  primarykey: Id
  records_per_page: 15
  order_by:
    -
      title: Id a-z
      criteria: Id ASC
    -
      title: Id z-a
      criteria: Id DESC
  search_default: Id
  referenced_entities:
    -
      entity: ValoresSN
    -
      entity: ValoresPrivacidad
    -
      entity: ValoresDchaIzq
    -
      entity: ValoresChangeFreq
  fieldGeneratorUrlFriendly: Codigo
  fieldGeneratorMetatagTitle: Codigo
  columns:
    -
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: Codigo
      field: Codigo
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    -
      title: Titulo
      field: Titulo
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: EsEstandar
      field: EsEstandar
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 1
        caption: EsEstandar
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Observaciones
      field: Observaciones
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: EsPredeterminado
      field: EsPredeterminado
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 2
        caption: EsPredeterminado
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Revisado
      field: Revisado
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 3
        caption: Revisado
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Publicar
      field: Publicar
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 4
        caption: Publicar
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteDesde
      field: VigenteDesde
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteHasta
      field: VigenteHasta
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: Privacidad
      field: Privacidad
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 5
        caption: Privacidad
        entity: ValoresPrivacidad
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Orden
      field: Orden
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: FechaPublicacion
      field: FechaPublicacion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: UrlAmigable
      field: UrlAmigable
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitle
      field: MetatagTitle
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagKeywords
      field: MetatagKeywords
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagDescription
      field: MetatagDescription
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitleSimple
      field: MetatagTitleSimple
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 6
        caption: MetatagTitleSimple
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitlePosicion
      field: MetatagTitlePosicion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 7
        caption: MetatagTitlePosicion
        entity: ValoresDchaIzq
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MostrarEnMapaWeb
      field: MostrarEnMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 8
        caption: MostrarEnMapaWeb
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: ImportanciaMapaWeb
      field: ImportanciaMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0,5
      validator:
        nullable: YES
        type: string
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: ChangeFreqMapaWeb
      field: ChangeFreqMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: monthly
      aditional_filter:
        order: 9
        caption: ChangeFreqMapaWeb
        entity: ValoresChangeFreq
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
