CommBancosOficinas:
  app: Comm
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: null
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: null
  controller: CONTROLADOR
  action: ACTION
  template: TEMPLATE
  parametros: PARAMETROS
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: 'Oficinas Bancarias'
  id_video: commbancosoficinas
  url_video: null
  feature_list: YES
  conection: 
  entity: CommBancosOficinas
  table: CommBancosOficinas
  primarykey: Id
  linkBy: IdBanco
  records_per_page: 15
  order_by:
    -
      title: 'Id a-z'
      criteria: 'Id ASC'
    -
      title: 'Id z-a'
      criteria: 'Id DESC'
  search_default: Id
  referenced_entities:
    - CommBancos
    - CommPaises
    - CommProvincias
    - CommMunicipios
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    IdBanco:
      title: IdBanco
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Codigo:
      title: Código
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '4', min: null, max: null, message: 'Valor Requerido' }
    Digito:
      title: Digito
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IdPais:
      title: Pais
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IdProvincia:
      title: Provincia
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IdMunicipio:
      title: Municipio
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Direccion
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: CodigoPostal
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Telefono
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Web:
      title: Web
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
