# Module: CoreUsuarios
# Document : modules\CoreUsuarios\config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 05.09.2012 08:17:43
#
---
CoreUsuarios:
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  feature_list: YES
  help_file: help.html.twig
  title: CoreUsuarios
  id_video: coreusuarios
  url_video: null
  conection: 'cpanel'
  entity: CoreUsuarios
  table: CoreUsuarios
  primarykey: Id
  records_per_page: 15
  order_by:
    -
      title: Id a-z
      criteria: Id ASC
    -
      title: Id z-a
      criteria: Id DESC
  search_default: Id
  referenced_entities:
    -
      entity: CorePerfiles
    -
      entity: CoreRoles
    -
      entity: CoreUsuariosTipos
    -
      entity: ValoresSN
    -
      entity: ValoresPrivacidad
    -
      entity: ValoresDchaIzq
    -
      entity: ValoresChangeFreq
  fieldGeneratorUrlFriendly: IdPerfil
  fieldGeneratorMetatagTitle: IdPerfil
  columns:
    -
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: IdPerfil
      field: IdPerfil
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 1
        caption: IdPerfil
        entity: CorePerfiles
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IdRol
      field: IdRol
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 2
        caption: IdRol
        entity: CoreRoles
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IdTipoUsuario
      field: IdTipoUsuario
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 3
        caption: IdTipoUsuario
        entity: CoreUsuariosTipos
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Login
      field: Login
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Password
      field: Password
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Apellidos
      field: Apellidos
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Nombre
      field: Nombre
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Email
      field: Email
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: TelefonoMovil
      field: TelefonoMovil
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
    -
      title: CambioPassword
      field: CambioPassword
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 4
        caption: CambioPassword
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Ips
      field: Ips
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: NLogin
      field: NLogin
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: YES
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: UltimoLogin
      field: UltimoLogin
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0000-00-00 00:00:00
      validator:
        nullable: YES
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: Observaciones
      field: Observaciones
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: EsPredeterminado
      field: EsPredeterminado
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 5
        caption: EsPredeterminado
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Revisado
      field: Revisado
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 6
        caption: Revisado
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Publicar
      field: Publicar
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 7
        caption: Publicar
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteDesde
      field: VigenteDesde
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteHasta
      field: VigenteHasta
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: Privacidad
      field: Privacidad
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 8
        caption: Privacidad
        entity: ValoresPrivacidad
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Orden
      field: Orden
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: FechaPublicacion
      field: FechaPublicacion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: UrlAmigable
      field: UrlAmigable
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitle
      field: MetatagTitle
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagKeywords
      field: MetatagKeywords
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagDescription
      field: MetatagDescription
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 250
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitleSimple
      field: MetatagTitleSimple
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 9
        caption: MetatagTitleSimple
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitlePosicion
      field: MetatagTitlePosicion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 10
        caption: MetatagTitlePosicion
        entity: ValoresDchaIzq
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MostrarEnMapaWeb
      field: MostrarEnMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 11
        caption: MostrarEnMapaWeb
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: ImportanciaMapaWeb
      field: ImportanciaMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0,5
      validator:
        nullable: YES
        type: string
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: ChangeFreqMapaWeb
      field: ChangeFreqMapaWeb
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: monthly
      aditional_filter:
        order: 12
        caption: ChangeFreqMapaWeb
        entity: ValoresChangeFreq
        method: fetchAll
        params: Descripcion
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
