# cpanel/entities/schema.yml

CpanAplicaciones:
  engine:
  charSet:
  comment: Sub apps del Cpanel
  columns:
    CodigoApp:   {type: string(15), notnull: true, index: unique}
    NombreApp:   {type: string(100), notnull: true}
    Descripcion: {type: string(100), notnul: true}
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:

CpanModulos:
  columns:
    CodigoApp:       { type: string(15), notnull: true, index: index, comment: 'db,CpanAplicaciones,CodigoApp' }
    NombreModulo:    { type: string(255), notnull: true, index: unique }
    Nivel:           { type: integer(4), notnull: true, default: 0 }
    Titulo:          { type: string(100), notnull: true }
    Descripcion:     { type: string(100), notnull: false, default: NULL }
    Funcionalidades: { type: string(255), notnull: true }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:
    CodigoApp : { ForeignEntity: CpanAplicaciones, ForeignId: CodigoApp }

CpanDocs:
  columns:
    Entity:      { type: string(255), notnull: true}
    IdEntity:    { type: integer(11), notnull: true}
    Type:        { type: string(10), notnull: true, index: index, comment: 'Abstract,TiposDocs,IDTipo' }
    IsThumbnail: { type: boolean, notnull: true, default: 0, index: index, comment: 'Abstract,ValoresSN,IDTipo' }
    PathName:    { type: string(255), notnull: true, default: ''}
    Name:        { type: string(255), notnull: true, default: ''}
    Extension:   { type: string(10), notnull: false, default: ''}
    Title:       { type: string(255), notnull: false}
    ShowCaption: { type: boolean, notnull: true, default: 0, index: index, comment: 'Abstract,ValoresSN,IDTipo' }
    MimeType:    { type: string(50), notnull: false }
    Size:        { type: int(11), notnull: true, default: 0}
    Height:      { type: int(11), notnull: true, default: 0}
    Width:       { type: int(11), notnull: true, default: 0}
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:
    IdMimeType: { ForeignEntity: TiposMime, ForeignId: IDTipo }

CpanPerfiles:
  columns:
    Perfil: { type: string(50), notnull: true }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:

CpanPermisos:
  columns:
    IdPerfil:        { type: integer, notnull: true, index: index, comment: 'db,CpanPerfiles,Id' }
    NombreModulo:    { type: string(255), notnull: true, index: index, comment: 'db,CpanModulos,NombreModulo' }
    Funcionalidades: { type: string(255), notnull: true }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:
    IdPerfil:     { ForeignEntity: CpanPerfiles, ForeignId: Id }
    NombreModulo: { ForeignEntity: CpanModulos, ForeignId: NombreModulo }

CpanRoles:
  columns:
    Rol: { type: string(50), notnull: true }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:

CpanFuncionalidades:
  columns:
    Codigo:      { type: string(15), notnull: true, index: unique}
    Titulo:      { type: string(100), notnull: true}
    Descripcion: { type: string(100), notnull: false}
    EsEstandar : { type: boolean, notnull: true, default: 0, index: index, comment: 'abstract,ValoresSN,IDTipo' }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:
    EsEstandar:  { ForeignEntity: ValoresSN, ForeignId: IDTipo }

CpanUsuariosTipos:
  columns:
    Descripcion: { type: string(50), notnull: true}
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:

CpanUsuarios:
  columns:
    Id:             { type: bigint(11), notnull: true, index: PRIMARY, autoIncrement: true, comment: 'db,PcaeUsuarios,Id'}
    IdPerfil:       { type: bigint(11), notnull: true, index: index, comment: 'db,CpanPerfiles,Id' }
    IdRol:          { type: bigint(11), notnull: true, index: index, comment: 'db,CpanRoles,Id' }
    IdTipoUsuario:  { type: bigint(11), notnull: true, index: index, comment: 'db,CpanUsuariosTipos,Id' }
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:
    Id:             { ForeignEntity: PcaeUsuarios, ForeignId: Id}
    IdPerfil:       { ForeignEntity: CpanPerfiles, ForeignId: Id}
    IdRol:          { ForeignEntity: CpanRoles, ForeignId: Id}
    IdTipoUsuario:  { ForeignEntity: CpanUsuariosTipos, ForeignId: Id}

CpanUrlAmigables:
  columns:
    UrlFriendly:   { type: string(255), notnull: true, index: Unique }
    Controller:    { type: string(255), notnull: true }
    Action:        { type: string(255), notnull: true }
    Template:      { type: string(255), notnull: false, default: NULL }
    Parameters:    { type: string(255), notnull: false, default: NULL }
    Entity:        { type: string(255), notnull: true}
    IdEntity:      { type: integer(11), notnull: true}
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations:

CpanVariables:
  comment: Variables de entorno y web del proyecto, subapps y modulos
  columns:
    IdProyectosApps: { type: bigint(11), notnull: true, index: index }
    Variable:        { type: string(255), notnull: true, index: index }
    Yml:             { type: text}
    <?php include '../cpanel/entities/schema/schemaColumnsCommon.yml'; echoln('');?>
  relations: