## CREAR EL ESQUEMA DE TODAS LAS APPS
##
## Este archivo hay que ir actualizandolo a medida que se creen más Apps
##
## @author Sergio Pérez <sergio.perez@albatronic.com>
## @copyright INFORMATICA ALBATRONIC, SL
## @date 25-01-2013

<?php include '../../entities/schema/schemaAppAlbm.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppBann.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppBlog.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppBoletin.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppComm.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppCpan.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppEncargos.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppEnl.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppEtiq.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppEven.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppGcon.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppNetworking.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppPcae.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppRrhh.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppServ.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppSld.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppVid.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppVisit.yml'; echoln('');?>
<?php include '../../entities/schema/schemaAppWidget.yml'; echoln('');?>
<?php include '../../entities/schema/schemaMapeoUrls.yml'; echoln('');?>