# PARAMETROS DE CONFIGURACION GLOBAL DE LA APLICACION
---
config:
  debug_mode: false

  # PARA MOSTRAR O NO EL BOTON DE LA AUDITORIA DE LOS FORMULARIOS
  audit_mode: true

  # CONTROL DE ACCESO POR IP
  ip_control: true

  # FORMATOS DE EXPORTACION DE INFORMACION
  export_types:
    - xls
    - xml
    - cvs
    - Yaml

  # ENTORNO DE LA APLICACION
  app:
    name: CPanel
    url: http://localhost/cpanel
    path: /cpanel
    framework: bin/albatronic/
    urlParent: http://localhost/pcae

  # SEMILLA PARA CONSTRUIR CLAVES MD5
  semillaMD5: verano

  # FIRMAS DE LA WEB
  signatures:
    links: 'www.articoestudio.com'
    services:
      'es': 'Diseño web,Venta Online,Posicionamiento web'
      'en': 'Web design,eCommerce,SEO'
      'fr': ''
    locations: 'Granada,Madrid,Malaga'

  # LONGITUD MÁXIMA PARA LAS URLS Y NOMBRES AMIGABLES
  maxLengthUrlsFriendly: 50
  # NUMERO MAXIMO DE PAGINAS
  numMaxPages: 100
  # NUMERO MAXIMO DE DOCUMENTOS
  numMaxDocuments: 0
  # NUMERO MAXIMO DE IMAGENES EN LA GALERIA
  numMaxGalery: 0
  # NUMERO MAXIMO DE VIDEOS
  numMaxVideos: 0
  # NUMERO MAXIMO DE AUDIOS
  numMaxAudios: 0
  # TIPOS DE ARCHIVOS PERMITIDOS PARA UPLOAD
  allowTypes: 'jpg,png,gif,pdf,docx,mp3,avi,pps'

  # MOTOR DE ENVIO DE CORREOS
  mailer:
    plugin_dir: bin/PHPMailer_v2.0.0/
    plugin_file: PhpMailer.class.php
    motor: PhpMailer
    socket: smtp
    host: mail.albatronic.com
    smtp_auth: true
    user_name: info@albatronic.com
    password: i1234o
    from: info@albatronic.com
    from_name: INFO
    timeout: 30

  # MOTOR PARA DOCUMENTOS EXCEL
  excel: /bin/PHPExcel/PHPExcel.php

  # MOTOR PARA GENERAR DOCUMENTOS PDF
  pdf: bin/pdf/fpdf.class.php

  # MOTOR PARA GRAFICOS DE BARRAS
  graph:
    -
      bin/jpgraph/src/jpgraph.php
    -
      bin/jpgraph/src/jpgraph_line.php
    -
      bin/jpgraph/src/jpgraph_bar.php

  # MOTOR DE TEMPLATES
  twig:
    motor: bin/Twig-1.7.0/lib/Twig/Autoloader.php
    templates_folder: modules
    debug_mode: true
    cache_folder: tmp
    charset: null

  # PROYECTOS Y CONEXIONES A LAS BASES DE DATOS
  # LA CARPETA DE CADA PROYECTO SE INDICA EL NODO FOLDER Y SE ENTIENDE
  # RESPECTO AL DOCUMENT_ROOT Y NO AL CPANEL
  #
  # EN PRODUCCION EL FOLDER SERÁ "/"
  conections:
    pcae:
      title: Portal Cloud Ártico Estudio
      description:
      folder: /pcae
      dbEngine: mysql
      host: localhost
      user: pcae
      password: pcae
      database: pcae
