# Module: Tiposfuncionalidad
# Document : modules\Tiposfuncionalidad\config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 03.08.2012 21:25:32
#
---
Tiposfuncionalidad:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Tiposfuncionalidad
  id_video: tiposfuncionalidad
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Tiposfuncionalidad
  table: tiposfuncionalidad
  primarykey: IDTipoFuncionalidad
  records_per_page: 15
  order_by: IDTipoFuncionalidad
  search_default: IDTipoFuncionalidad
  referenced_entities:
    -
      entity: ValoresSN
    -
      entity: ValoresPrivacidad
  columns:
    -
      title: IDTipoFuncionalidad
      field: IDTipoFuncionalidad
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: Codigo
      field: Codigo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    -
      title: Titulo
      field: Titulo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Observaciones
      field: Observaciones
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: PrimaryKeyMD5
      field: PrimaryKeyMD5
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: EsPredeterminado
      field: EsPredeterminado
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 1
        caption: EsPredeterminado
        entity: ValoresSN
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Revisado
      field: Revisado
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 2
        caption: Revisado
        entity: ValoresSN
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Publicar
      field: Publicar
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 3
        caption: Publicar
        entity: ValoresSN
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteDesde
      field: VigenteDesde
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: VigenteHasta
      field: VigenteHasta
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: Deleted
      field: Deleted
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 4
        caption: Deleted
        entity: ValoresSN
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: DeletedBy
      field: DeletedBy
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: DeletedAt
      field: DeletedAt
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: Privacidad
      field: Privacidad
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 5
        caption: Privacidad
        entity: ValoresPrivacidad
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Orden
      field: Orden
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Imagenes
      field: Imagenes
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: FechaPublicacion
      field: FechaPublicacion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: datetime
        length: 
        min: null
        max: null
        message: Valor Requerido
    -
      title: UrlAmigable
      field: UrlAmigable
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: NumeroVisitas
      field: NumeroVisitas
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitle
      field: MetatagTitle
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagKeywords
      field: MetatagKeywords
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagDescription
      field: MetatagDescription
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitleSimple
      field: MetatagTitleSimple
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 6
        caption: MetatagTitleSimple
        entity: ValoresSN
        method: fetchAll
        params: null
        type: select
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MetatagTitlePosicion
      field: MetatagTitlePosicion
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 7
        caption: MetatagTitlePosicion
        entity: ValoresSN
        method: fetchAll
        params: null
        type: select
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: MostrarEnMapaWeb
      field: MostrarEnMapaWeb
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 8
        caption: MostrarEnMapaWeb
        entity: ValoresSN
        method: fetchAll
        params: null
        type: select
        operator: =
        event: null
      validator:
        nullable: YES
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: ImportanciaMapaWeb
      field: ImportanciaMapaWeb
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: YES
        type: string
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: ChangeFreqMapaWeb
      field: ChangeFreqMapaWeb
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: YES
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
