## YAML Template.
---
Error404:
  includesHead:
    lapTopPublic:
      twigCss: Error404/css.html.twig
      twigJs: Error404/js.html.twig
      
    lapTopPrivate:
      twigCss: 
      twigJs: 

    mobilePublic:
      twigCss: 
      twigJs: 
      
    mobilePrivate:
      twigCss: 
      twigJs: 
  
  #Variables Web
  includesVarWeb: 

